FROM python:3.12.8-slim-bookworm

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    apt-get update -y && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    software-properties-common \
    ffmpeg libsm6 libxext6 \
    git \
    && curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -x - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt
RUN --mount=type=cache,target=/root/.cache/ms-playwright playwright install chromium --with-deps
