@host = http://127.0.0.1
@port = 4000
@email = user1@example.com
@password = password123

### Login request
# @name login
POST {{host}}:{{port}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{"email":"{{email}}", "password": "{{password}}"}

### Response

@accessToken = {{login.response.body.$.access_token}}

### Create Organization request
# @name createOrganization
POST {{host}}:{{port}}/organization/create HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{"name": "test org", "website": "https://test.com"}

### Response

@orgId = {{createOrganization.response.body.$.id}}

### Add Organization user
# @name createOrganization
POST {{host}}:{{port}}/organization/{{orgId}}/add_user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{"email": "user2@example.com"}
