@host = http://127.0.0.1
@port = 4000
@email = markus@thirdcognition.com
@password = tc_123_admin

### Login request
# @name login
POST {{host}}:{{port}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{"email":"{{email}}", "password": "{{password}}"}

### Response
@accessToken = {{login.response.body.$.access_token}}

### Fetch Mailchimp Lists request
# @name fetchMailchimpLists
GET {{host}}:{{port}}/communication/mailchimp/lists HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

### Fetch Mailchimp Templates request
# @name fetchMailchimpTemplates
GET {{host}}:{{port}}/communication/mailchimp/templates HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

# @transcript_id = 52a69cd8-3818-46aa-a3d7-302b5b17271c
@transcript_id = c793c1d9-22cc-44df-8c87-429f8f185066

### Fetch Transcript Email
# @name sendTranscriptEmail
POST {{host}}:{{port}}/communication/send-transcript-email HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

["{{transcript_id}}"]

### Send Transcript Notification
# @name sendTranscriptNotification
POST {{host}}:{{port}}/communication/send-transcript-push-notifications HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}



# ["{{transcript_id}}"]
