@host = http://127.0.0.1
@port = 4000
@email = user1@example.com
@password = password123

### Login request
# @name login
POST {{host}}:{{port}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{"email":"{{email}}", "password": "{{password}}"}

### Response
@accessToken = {{login.response.body.$.access_token}}

### Create Journey request
# @name createJourney
POST {{host}}:{{port}}/journey/ HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "New Journey",
  "description": "Description of the new journey"
}

### Response
@journeyId = {{createJourney.response.body.$.journey_id}}

### Create Journey Item request
# @name createJourneyItem
POST {{host}}:{{port}}/journey_item/ HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "journey_id": "{{journeyId}}",
  "disabled": false
}

### Response
@journeyItemId = {{createJourneyItem.response.body.$.journey_item_id}}

### Create Journey Item Version request
# @name createJourneyItemVersion
POST {{host}}:{{port}}/journey_item_version/ HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "journey_id": "{{journeyId}}",
  "journey_item_id": "{{journeyItemId}}",
  "name": "Version 1",
  "disabled": false
}

### Response
@journeyItemVersionId = {{createJourneyItemVersion.response.body.$.journey_item_version_id}}

### Get Journey Item Version request
# @name getJourneyItemVersion
GET {{host}}:{{port}}/journey_item_version/{{journeyItemVersionId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

### List Journey Item Versions request
# @name listJourneyItemVersions
GET {{host}}:{{port}}/journey_item_versions/ HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

### Update Journey Item Version request
# @name updateJourneyItemVersion
PUT {{host}}:{{port}}/journey_item_version/{{journeyItemVersionId}} HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "journey_id": "{{journeyId}}",
  "name": "Updated Version 1",
  "disabled": true
}

### Delete Journey Item Version request
# @name deleteJourneyItemVersion
DELETE {{host}}:{{port}}/journey_item_version/{{journeyItemVersionId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}
