@host = http://127.0.0.1
@port = 4000
@email = user1@example.com
@password = password123

### Login request
# @name login
POST {{host}}:{{port}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{"email":"{{email}}", "password": "{{password}}"}

### Response
@accessToken = {{login.response.body.$.access_token}}

### Journey Template request
# @name journeyTemplate
POST {{host}}:{{port}}/journey/match_with_template HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "role_title": "Marketing Manager",
  "role_description": "Seeking an experienced Marketing Manager to lead our team, develop strategies, manage campaigns, and drive brand growth. Must have 5+ years of experience and strong leadership skills."
}

### Response
@templateId = {{journeyTemplate.response.body.$.template_id}}

### Journey Create From Template request
# @name journeyCreateFromTemplate
GET {{host}}:{{port}}/journey/from_template/{{templateId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

@journeyId = {{journeyCreateFromTemplate.response.body.$.journey_id}}
@journeyVersionId = {{journeyCreateFromTemplate.response.body.$.journey_version}}

### Journey Copy request
# @name journeyCopy
GET {{host}}:{{port}}/journey/copy/{{journeyVersionId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}
