@host = http://127.0.0.1
@port = 4000
@email = user1@example.com
@password = password123

### Login request
# @name login
POST {{host}}:{{port}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{"email":"{{email}}", "password": "{{password}}"}

### Response
@accessToken = {{login.response.body.$.access_token}}

### Response
@orgId = 2f26ba37-3555-4fc8-a274-38afe6259311

### Create Organization User request
# @name createOrganizationUser
POST {{host}}:{{port}}/organization/{{orgId}}/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{"email": "user2@example.com"}

### Response
@userId = {{createOrganizationUser.response.body.$.user_id}}

### Get Organization User request
# @name getOrganizationUser
GET {{host}}:{{port}}/organization/{{orgId}}/user/{{userId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

### List Organization Users request
# @name listOrganizationUsers
GET {{host}}:{{port}}/organization/{{orgId}}/users HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

### Update Organization User request
# @name updateOrganizationUser
PUT {{host}}:{{port}}/organization/{{orgId}}/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{"user_id": "{{userId}}", "is_admin": true, "disabled": false}

### Delete Organization User request
# @name deleteOrganizationUser
DELETE {{host}}:{{port}}/organization/{{orgId}}/user/{{userId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}
