@host = http://127.0.0.1
@port = 4000
@email = user1@example.com
@password = password123

### Login request
# @name login
POST {{host}}:{{port}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{"email":"{{email}}", "password": "{{password}}"}

### Response
@accessToken = {{login.response.body.$.access_token}}

### Start Test Task request
# @name startTestTask
POST {{host}}:{{port}}/system/start_test_task HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}

### Response
@taskId = {{startTestTask.response.body.$.task_id}}

### Check Task Status request
# @name checkTaskStatus
GET {{host}}:{{port}}/system/task_status/{{taskId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}
